# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""Strip directory sections from a Next.js agents-md INDEX.md.

Run with --help for usage.
"""

import argparse
import re
import sys
from pathlib import Path

START_MARKER = "<!-- NEXT-AGENTS-MD-START -->"
END_MARKER = "<!-- NEXT-AGENTS-MD-END -->"


def parse_args() -> argparse.Namespace:
    """Build the CLI parser and return the parsed arguments."""
    parser = argparse.ArgumentParser(
        prog=sys.argv[0],
        description=(
            "Strip directory sections from a Next.js agents-md INDEX.md and verify that\n"
            "remaining entries match the docs on disk. "
            "Run after `npx @next/codemod agents-md`\n"
            "to remove documentation this project does not use (e.g. Pages Router).\n"
            "\n"
            "The index is a single pipe-delimited line between HTML comment markers.\n"
            "Each directory entry looks like `prefix:{file.mdx,...}` or\n"
            "`prefix/sub:{file.mdx,...}`. Requires at least one of --remove or --verify."
        ),
        epilog=(
            "examples:\n"
            "  # Remove Pages Router and Community docs (verifies automatically)\n"
            "  uv run %(prog)s .nextjs-docs/INDEX.md \\\n"
            "      --remove 02-pages --remove 04-community\n"
            "\n"
            "  # Verify only — read-only, reports index/disk discrepancies\n"
            "  uv run %(prog)s .nextjs-docs/INDEX.md --verify\n"
            "\n"
            "output:\n"
            "  ✅ Success: ...    Operation completed (exit 0)\n"
            "  💡 Info: ...       Nothing to do, file unchanged (exit 0)\n"
            "  ❌ Error: ...      Something is wrong (exit 1)\n"
            "\n"
            "notes:\n"
            "  --remove always verifies after stripping — no need to add --verify.\n"
            "  --remove is idempotent — safe to re-run; "
            "already-removed prefixes show 💡.\n"
            "  index.mdx files are excluded from verification (not tracked in the index)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "index_file",
        type=Path,
        help="agents-md INDEX.md generated by @next/codemod",
    )
    parser.add_argument(
        "--remove",
        action="append",
        metavar="PREFIX",
        help=(
            "directory prefix to strip — "
            "removes PREFIX:{...} and PREFIX/...:{...} entries, "
            "then verifies the result (repeatable)"
        ),
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help=(
            "read-only check — reports files in the index missing from disk "
            "and files on disk missing from the index (excludes index.mdx)"
        ),
    )
    args = parser.parse_args()
    if not args.remove and not args.verify:
        parser.error("at least one of --remove or --verify is required")
    return args


def matches_prefix(segment: str, prefixes: list[str]) -> bool:
    """Check whether a segment is a directory entry matching any prefix."""
    candidates = tuple(f"{p}{sep}" for p in prefixes for sep in (":", "/"))
    return segment.startswith(candidates)


def find_agents_block(content: str) -> re.Match[str]:
    """Find the agents-md block and return the regex match."""
    pattern = re.compile(rf"({re.escape(START_MARKER)})(.*?)({re.escape(END_MARKER)})")
    match = pattern.search(content)
    if not match:
        print("❌ Error: Could not find agents-md markers in file.")
        sys.exit(1)
    return match


def validate_format(content: str) -> None:
    """Pre-flight check that the index follows the expected agents-md format."""
    match = find_agents_block(content)
    segments = match.group(2).split("|")

    if not any(s.startswith("root: ") for s in segments):
        print("❌ Error: No 'root:' segment found in index.")
        sys.exit(1)

    dir_segments = [s for s in segments if ":{" in s]
    if not dir_segments:
        print("❌ Error: No directory entries (prefix:{files}) found in index.")
        sys.exit(1)

    for seg in dir_segments:
        if not seg.endswith("}"):
            print(f"❌ Error: Malformed segment (missing closing '}}'): {seg[:80]}")
            sys.exit(1)


def parse_segments(inner: str) -> tuple[Path, set[str]]:
    """Extract the root path and set of indexed file paths from the inner content.

    Assumes validate_format has already verified a 'root: ' segment exists.
    """
    segments = inner.split("|")
    root_seg = next(s for s in segments if s.startswith("root: "))
    root = Path(root_seg.removeprefix("root: "))
    indexed: set[str] = set()
    for seg in segments:
        if ":{" in seg:
            dir_part, files_part = seg.split(":{", 1)
            for f in files_part.rstrip("}").split(","):
                indexed.add(f"{dir_part}/{f}")
    return root, indexed


def strip_sections(content: str, prefixes: list[str]) -> tuple[str, int]:
    """Parse the index line, filter out matching sections, and reassemble."""
    match = find_agents_block(content)
    start, inner, end = match.group(1), match.group(2), match.group(3)
    segments = inner.split("|")
    filtered = [s for s in segments if not matches_prefix(s, prefixes)]
    removed_count = len(segments) - len(filtered)
    return (
        content[: match.start()]
        + start
        + "|".join(filtered)
        + end
        + content[match.end() :],
        removed_count,
    )


def verify_index(content: str) -> bool:
    """Check that indexed files match the docs directory. Returns True if valid."""
    match = find_agents_block(content)
    root, indexed_files = parse_segments(match.group(2))

    docs_dir = root.resolve()
    if not docs_dir.is_dir():
        print(f"❌ Error: Docs directory not found: {docs_dir}")
        sys.exit(1)

    disk_files = {
        p.relative_to(docs_dir).as_posix()
        for p in docs_dir.rglob("*.mdx")
        if p.name != "index.mdx"
    }

    in_index_not_disk = sorted(indexed_files - disk_files)
    on_disk_not_index = sorted(disk_files - indexed_files)

    if in_index_not_disk:
        print(f"❌ Error: In index but NOT on disk ({len(in_index_not_disk)}):")
        for f in in_index_not_disk:
            print(f"  - {f}")

    if on_disk_not_index:
        print(f"❌ Error: On disk but NOT in index ({len(on_disk_not_index)}):")
        for f in on_disk_not_index:
            print(f"  + {f}")

    if not in_index_not_disk and not on_disk_not_index:
        print(
            f"✅ Success: Index is complete and accurate. "
            f"{len(indexed_files)} files verified."
        )
        return True

    return False


def main() -> None:
    """Run the strip/verify workflow based on CLI arguments."""
    args = parse_args()
    index_file: Path = args.index_file

    if not index_file.exists():
        print(f"❌ Error: {index_file} not found.")
        sys.exit(1)

    content = index_file.read_text()
    validate_format(content)

    if args.remove:
        result, removed_count = strip_sections(content, args.remove)
        if result == content:
            print(f"💡 Info: No sections matched prefixes: {', '.join(args.remove)}")
        else:
            index_file.write_text(result)
            print(
                f"✅ Success: Removed {removed_count} section(s) "
                f"matching: {', '.join(args.remove)}"
            )
            content = result
        if not verify_index(content):
            sys.exit(1)
    elif args.verify:
        if not verify_index(content):
            sys.exit(1)


if __name__ == "__main__":
    main()
